crimsobot/crimsoBOT

crimsobot/bot.py
So that bad usage does not trigger a cooldown and frustrate the user.
Please.
I don't want to eat glass.
=> de-bullshit cooldown handling

crimsobot/bot.py, crimsobot/cogs/chat.py, crimsobot/utils/markov.py, crimsobot/utils/tarot.py
-Heavy sync operations are wrapped asynchronously
-Scatterbrain uses rewrite syntax now, and no longer has a list comp
-Some style changes to appease PEP8
-Bugs with my last try at this have been fixed
-Some other stuff that I really can't remember
-Fixed a bug with tarot
=> Fix the things that fixing things broke and also fix another thing

crimsobot/utils/games.py
Small change to cringo scoring to keep full card bonus from being counted multiple times
=> cringo scoring fix

crimsobot/cogs/games.py, crimsobot/utils/games.py
- join with reaction instead of message
- multiple matches in a single message allowed
- "leaderboard" changed to "scoreboard" in various places to accommodate future leaderboard function
- user interaction (i.e. messages to user) updated and enriched
=> Join, match, user interaction updated

crimsobot/cogs/admin.py
Updated info embed with Weebly store info
=> >info update

crimsobot/cogs/games.py
Small fixes to larger exploit fix earlier today:
1. Not checking out users properly
2. Re-adjusted game timers (had shortened them for faster beta testing)
=> Cringo security patch

crimsobot/cogs/games.py
=> small error in initial card sending

crimsobot/cogs/chat.py, crimsobot/utils/markov.py
- scatterbrain: no more disk i/o, error handling
- general code cleanup for utils/markov.py
=> Markov utils cleanup, scatterbrain error handling

.gitignore, crimsobot/cogs/cringo.py, crimsobot/utils/cringo.py
No functionality changes, only housekeeping.
=> Fixed repeat no-join msg, CringoPlayer() class fix

crimsobot/cogs/admin.py, crimsobot/cogs/games.py, crimsobot/utils/games.py
Cosmetic changes to embeds and typos, and threw in a few more answers for `>crimsoball` while I was at it.
=> Fixed cball & daily embeds, other small cosmetics

.github/FUNDING.yml
Adding sponsor link for the Patreon
See https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository for info
=> Add funding config to repo

crimsobot/bot.py, crimsobot/cogs/admin.py, crimsobot/cogs/chat.py, crimsobot/cogs/cringo.py, crimsobot/cogs/games.py, crimsobot/cogs/image.py, crimsobot/cogs/mystery.py, crimsobot/cogs/text.py, crimsobot/cogs/utilities.py, crimsobot/utils/astronomy.py, crimsobot/utils/cringo.py, crimsobot/utils/games.py, crimsobot/utils/image.py, crimsobot/utils/markov.py, crimsobot/utils/tools.py
Getting linting and static analysis in check so that CI builds can pass.
=> Another swipe of the lint filter

.github/workflows/main.yaml
=> Setup GitHub Actions

crimsobot/bot.py, crimsobot/cogs/chat.py, crimsobot/cogs/games.py
1) In all places where a utils/markov.py chat function is called, `async_wrap()` is utilized.
2) Improvements to chat functionality
a) when bot is pinged,
b) when it's time to chat randomly,
c) `>scatterbrain`
3) Added a markov element to `>crimsoball`
=> utils/markov.py:async_wrap(); improved chat

crimsobot/cogs/cringo.py
One line! A branch for one line!
=> Missing arg causing game to crash in certain case

crimsobot/utils/cringo.py
New and improved Cringo! marker emojis are sitting in a secret Discord server, and they're ready to be deployed!
=> Cringo marker update!

.github/workflows/main.yaml
I've added continuous deployment!
User and key has been set up and configured properly on the bot host.
=> Add CD to actions workflow

crimsobot/cogs/utilities.py
=> Awful poll function

crimsobot/cogs/utilities.py
20 s guild-level cooldowns for poll and tally, plus a small nitpick of Kaylynn's addressed
=> Cooldowns to combat the inevitable spam

crimsobot/cogs/cringo.py, crimsobot/cogs/games.py, crimsobot/utils/games.py, crimsobot/utils/guess_leaderboard.py, crimsobot/utils/tools.py
Updated guessmoji stats and leaderboards to clear up confusion between guessmoji and cringo stats. When guessmoji was created, it was the only luck-based game (and the only way to win crimsoCOIN). This update should clear up the differences.
=> Update guessmoji stats and leaderboards

crimsobot/cogs/utilities.py
1) No more blank questions or answers show up in polls
2) Poll will not show up if there are fewer than 2 choices given
3) If no question given, then it's a "quick poll"
=> Checks to ensure a question, >1 non-blank choice

crimsobot/utils/image.py
=> Fix error in make_color_img()'s usage of image_to_buffer()

crimsobot/cogs/image.py, crimsobot/utils/image.py
Continuing to work through the code to place returned images in embeds.
=> Image cog commands in embeds

crimsobot/bot.py
Housekeeping update for `crimsobot/bot.py`.
1. **Switched to f-strings**: Was a mess of various string formatting methods.
2. **DRYed up `on_command_error()`**: This function is now more streamlined, with a new error embed and more readable output in terminal.
3. **Fixed `on_guild_join()`**: Bot owners now notified via DM when bot is added to a server. Was failing before due to `TypeError: object User can't be used in 'await' expression` for `get_user()`.
=> DRYed up code, f-strings, fixed `on_guild_join`

.github/workflows/main.yaml, README.rst, poetry.lock, pyproject.toml
=> Bump requirement to Python 3.7 and update dependencies

crimsobot/cogs/games.py
`bubblewrap` is a simple fidget/stress relief game.
=> Add bubble wrap game to Games cog.

poetry.lock, pyproject.toml
This PR reverts a dependency change that broke things on crimsobot's host.
=> Revert bad dependency change

crimsobot/bot.py, crimsobot/cogs/cringo.py, crimsobot/cogs/image.py, crimsobot/handlers/__init__.py, crimsobot/handlers/games.py, crimsobot/utils/cringo.py, crimsobot/utils/tools.py, poetry.lock, pyproject.toml
Refactors Cringo! and prepares for upcoming intents changes.
Needs review.
=> Cringo! refactor and intents changes

crimsobot/cogs/cringo.py, crimsobot/cogs/games.py
=> Fix .leave bugs and do some cleanup

crimsobot/cogs/cringo.py
Fixes a few bugs. Exactly what it says on the tin.
=> Fix joining/leaving bugs

crimsobot/cogs/utilities.py
Just attach an image to the >poll command, and enjoy.
- Could also throw an error if there's more than one image, if you wanted? (but why?)
- Just Works™ if the attachment's not an image
=> Add images in >poll and >polltally

crimsobot/cogs/utilities.py
Looks like this fixes the new unbound local variable error when tallying a poll that lacks an image.
=> Fix >tally

crimsobot/cogs/admin.py
exactly-what-it-says-on-the-tin.gif
=> New store link!

crimsobot/bot.py
=> Only invoke commands if a response is possible

crimsobot/cogs/mystery.py, crimsobot/data/tarot/deck.yaml, crimsobot/utils/tarot.py
Brick by brick I am adding to the tarot deck, giving each card a long-form description for how to interpret it when it is dealt in the reversed position. Once the deck is amended, I will add the new description to the `>tarot card` embed.
=> Tarot reversed long

crimsobot/cogs/image.py
=> Literally one comma

.github/workflows/codeql.yaml
=> Run CodeQL only on schedule

crimsobot/bot.py
=> FIx up DMs to bot; no more CommandNotFound in logs

crimsobot/cogs/games.py
Last one today, I promise! Simple fix.
=> Fix bubblewrap's ability to choose a random emoji

crimsobot/utils/cringo.py
Optimize flow of gameplay for period of misbehavior of codebase under the current phase.
=> Refactor ziplist to pass when arg_1 = 1.

crimsobot/utils/cringo.py
Reverts crimsobot/crimsoBOT#121. We've had our fun.
=> Revert "Refactor ziplist to pass when arg_1 = 1."

.pre-commit-config.yaml, crimsobot/utils/tools.py
* pre-commit environment didn't have numpy
* fix crimbed to use Empty sentinel
=> Post-update fixes

crimsobot/cogs/utilities.py
https://cdn.discordapp.com/attachments/574795608406097940/915248944412512296/unknown.png never again
=> Support hex codes missing the "#"

crimsobot/cogs/games.py
Small change to adjust winnings
=> Winnings fix

crimsobot/utils/games.py
A few little fixes to Wordle stats.
=> Histogram fixes, embed formatting

crimsobot/cogs/admin.py
Quick fix: Applies `crimsplit()` to the `servers()` function; we're in too many servers!
=> Apply crimsplit() to servers() function

crimsobot/utils/image.py, poetry.lock, pyproject.toml
Adds a conditional to `fetch_image()` in `utils/image.py` which looks for a Tenor link--which display in Discord as a GIF despite being a link to a Web page--and, if a Tenor link, then scrapes the GIF URL from the Tenor page. A new dependency, BeautifulSoup, has been added to help pull data out of the fetched HTML.
=> utils/image.py: fetch_image() scrape from Tenor

crimsobot/cogs/image.py, crimsobot/data/img/__init__.py, crimsobot/data/img/rules.yaml, crimsobot/utils/image.py
Addresses a few issues with image processing.
- `data/img`: Processing rules moved to new YAML, `__init__.py` updated.
- `utils/image.py`: GIF resizing algorithm retooled to be (hopefully) faster; progress messages restyled.
- `cogs/image.py`: Superfluous `CommandInvokeError` embed avoided.
=> Rework of image utils: gif resize, embeds, params

cli.py, crimsobot/bot.py, crimsobot/cogs/mystery.py, crimsobot/utils/tarot.py
Found this in an old branch locally, let's merge it!
=> Just some small improvements

crimsobot/utils/games.py
A simple change, and a good one! Addresses "issue" [144](https://github.com/crimsobot/crimsoBOT/issues/144).
=> Change made! + Bonus embed titles for the losers

crimsobot/bot.py, crimsobot/cogs/image.py, crimsobot/data/img/rules.yaml, crimsobot/exceptions.py, crimsobot/utils/image.py
A feature request from @the-garlic-os: process image commands from replies!
This endeavor has really highlighted the need for some reorganization of the image cog and util, but that's for a future PR.
=> Image commands from replies

crimsobot/cogs/utilities.py
=> Add random color functionality

crimsobot/bot.py, crimsobot/cogs/utilities.py, crimsobot/exceptions.py, crimsobot/utils/astronomy.py
- Input parsing and checking moved out of cog and into utils.
- Small embed edits.
- Image size reduced to 600 x 600 to be more legible inside of embed.
- Custom error message added for bad zoom level.
=> Map input parsing and checking moved to utils; embed and image size tweaks

config.example.py, crimsobot/cogs/admin.py
- Link to Square store removed
- The empty promise of a crimsoBOT sticker for new patrons toned down to an empty hopeful suggestion.
- Permissions integer moved to `config.py` where it belongs.
=> Updated >info embed

crimsobot/cogs/cringo.py, crimsobot/utils/cringo.py
A few housekeeping details:
- User name formatting to exclude discriminator
- Final coin display formatting
- Join game embed made (hopefully) more clear 
- Help text updated
- Unused function in `utils/cringo.py` removed.
=> Formatting, embed, help text updates

crimsobot/data/img/rules.yaml, crimsobot/utils/image.py
Increase max filesize from 8 MB to 25 MB.
=> Increased file size limit

crimsobot/data/img/rules.yaml
=> Fix typos in lyrics
