crimsobot/cogs/admin.py
Limits all potentially revealing commands to bot admins.
=> Add admin checks

crimsobot/bot.py
Functionality is identical. Assigning message to a variable name for deletion is not required as the delete_after kwarg in Messageable.send can be used.
=> remove unneeded asyncio.sleep

crimsobot/bot.py
using qualified_name as opposed to name because qualified_name will still return the correct string even if a subcommand is used
=> give command name on error prompt

crimsobot/cogs/games.py
If the only winner of guessmoji also voted multiple times, the game would proceed as if there were a winner, but the length of the list of winners would be 0, causing a failute in winner_list() in utils/games. 
This fixes that!
=> Handle special case of multi votes in guessmoji

crimsobot/cogs/games.py
Small remnant from old cringo join mechanism caused crash if bot tried to DM instructions to user who did not allow DMs.
=> Small bug fix

crimsobot/cogs/games.py, crimsobot/utils/tools.py
A user found an exploit in Cringo! where, by starting _n_ games at once and simply by joining one of them, the user could play _n_ games at once in a less-than-honest manner, as detailed below:
> So first I noticed that cringo can be exploited that it can run several instances of a game at the same time. When I type >cringo in n text channels, and then press join emoji it gives me n cards (also there is a bug with this, I only need to press join emoji on one channel, and it join me for a game in all channels)
> next thing is that the dm commands (.a1 . b2 etc) are sharable between all games, for example if a1 is a match on one card and not on the second the command still recognizes it on both cards, no way on describe on what card I wanted to put a match command on
> then because I can …
=> Cringo! exploit fixed

crimsobot/cogs/games.py, crimsobot/utils/games.py
Some users were inputting ".a1 a2 a3 a4 b1 b2 b3 b4 c1 c2 c3 c4 d1 d2 d3 d4" for each round because the penalty for mismatches was low enough to ignore. Now if a user plays this way, they will be docked more points and possibly removed from the game.
=> "Lazy play" exploit closed.

crimsobot/cogs/games.py
1) Blocking DMs from the bot mid-game would (a) cause the game to crash and (b) not checkout the user, disallowing them from joining a new game. This should be handled now.
2) Allows a player to type ".leave" during a round to leave the game voluntarily.
3) A few processes wrapped into functions.
=> Handle DM blocking, allow players to leave game

crimsobot/cogs/games.py
1) If a user was not added by clicking the join emoji, then they are scooped up at the end of the countdown and added to the game.
2) process_player_response() in cogs/games.py will no longer listen to players who have left. Messages from players who left during a round were still having their messages passed to this function until that round ended, so they could crash the game by sending another message beginning with `.`.
=> Cringo small fixes

crimsobot/utils/image.py
This fix lets bigmoji find the file for emojis that have a "non-fully-qualified twin" so to speak.
For example, some emojis existed as Unicode symbols before the release of Emoji v1.0. They have a small difference in their code points. For example (from http://unicode.org/Public/emoji/5.0/emoji-test.txt):
```
263A FE0F                                  ; fully-qualified     # ☺️ smiling face
263A                                       ; non-fully-qualified # ☺ smiling face
```
The files in data/emojis for these "twin" pairs do NOT have the "-fe0f" at the end of the filename, so bigmoji couldn't find them when queried. Now that' fixed!
=> Bug fix for "old" emojis (pre-Emoji v1.0)

crimsobot/cogs/cringo.py, crimsobot/utils/cringo.py
Tiny fixes.
1) Concurrency decorators for the `@cringo.commands()`.
2) A leftover line of code form the cringo monte carlo simulation was removed, which was blocking users from being awarded points for a full card.
3) Various housekeeping that I've probably already forgotten that I've done.
=> Concurrencies added, full card error fixed

crimsobot/cogs/admin.py, crimsobot/utils/image.py
There is some disagreement between Discord and Twemoji on which emojis should have the variation selector `-fe0f` at the end of their Unicode sequence. In an earlier fix (bigmoji-fix) I fixed one special case of this disagreement ("old" emojis, pre-Emoji v1.0) but broke another (gender and skin tone variations). Both appear to be working with this fix.
=> Earlier fix broke some functionality; now restored.

crimsobot/cogs/mystery.py, crimsobot/data/tarot/suits.yaml, crimsobot/utils/tarot.py, crimsobot/utils/tools.py
Tarot functions now return embeds. I was mistaken before in thinking that attachments could not be included in embeds. To include an image in an embed, one needs a URL. For attachments, that URL can be `'attachment://[filename]'`.
`/utils/tools.py/crimbed` has been updated to more easily allow image URLS and attachments to be included, and this new functionality is used only in the Tarot cog so far. This update adds only kwargs `image_url` and `attachment` and does not break other functions using `crimbed()`.
This augmented `crimbed()` functionality will be put to use in the Image cog in a future PR.
=> Updated tarot cog to embeds; updated tools/crimbed

.github/workflows/main.yaml
Discovered while reviewing #67 that we're not running CI on PRs from forks... according to the Actions docs, this should fix it.
=> Allow CI on forks

.gitignore, crimsobot/bot.py, crimsobot/cogs/text.py
A bug in the `on_message` that has the bot respond to when it is mentioned was having the bot respond to messages it sent itself if that message included a mention. This bug was exploited via the `emojiclock` function. `emojiclock` will allow non-emoji input, and users were using a mention of the bot as the "emoji." This was done without end by certain users, causing the increased load issue.
This fix adds a user cooldown to `emojiclock` as well as disallowing the bot to respond to its own messages when those messages contain a mention of the bot.
=> Stopgap to prevent spam of `emojiclock`

crimsobot/utils/tarot.py
Embed field will now have an invisible character as a name instead of `''`
=> Fix >tarot one error

.github/workflows/main.yaml
https://github.com/crimsobot/crimsoBOT/commit/88f1414ce8d9d32a20ba4a04b6871c2d5afe2bc9 introduced a regression in which Actions runs were happening twice for any open PRs.
This revises the triggers to only run on `push` to `master` (which also still runs the deploy) and on any `pull_request` event.
=> Don't run pipeline twice on PRs

crimsobot/cogs/reactions.py
Facts with subjects of bodies of zero length were being added, and they cannot be accessed or inspected.
=> Disallow facts with subject or body of length <1

crimsobot/cogs/reactions.py
Does exactly what the title says - fixes a typo in the >facts about footer.
=> Fix typo in >facts about

crimsobot/utils/fact_leaderboard.py
When the subject of a fact contained a user mention, the subject would not display well on the leaderboard, e.g. '<@123...678>'. These user mention strings are now detected and converted to usernames, e.g. '@username#1234'.
=> Fact lb fix

crimsobot/cogs/games.py
Does exactly what it says on the tin. Adds a single alias to the `give` command for convenience.
=> Add alias "pay" to give command

crimsobot/bot.py
A new feature introduced in discord.py 1.4 allows us to keep mentions but remove the notifying aspect of them. This means that the previous form of markov scrubbing is no longer required - this PR removes the old form of mention scrubbing from markov, and instead uses the notification nullification approach.
=> Add allowed_mentions to markov messages

crimsobot/bot.py, crimsobot/cogs/mystery.py, crimsobot/exceptions.py, crimsobot/utils/tarot.py
This PR makes tarot a little bit nicer.
Changes include:
- Creation of the coveted exceptions.py (which will no doubt be expanded upon later)
- Allowing ``>tarot card`` to be used with the name of a card or the card picking UX. This uses some fancy fuzzy matching so you can afford to make small mistakes in your spelling! Mobile users rejoice.
- Some shuffling of functionality around so that it's tidier.
- Some bug crunching.
=> Tarot rejuvenation

crimsobot/cogs/reactions.py
This PR makes fact formatting more consistent and lets you use ``>fact`` with an argument as a shorthand for ``>fact about``.
=> Tiny facts changes

crimsobot/cogs/cringo.py, crimsobot/cogs/games.py
Very small change. This one makes the cringo and guess leaderboards subcommands of their respective commands.
=> Move leaderboard commands to subcommands

crimsobot/bot.py
This helps avoid issues related to invocations and cooldowns that don't make much sense. It's a small and easy fix.
=> Only invoke commands if a response is possible

crimsobot/cogs/cringo.py
An `AttributeError` in `remove_from_game` breaks the game loop and causes a crash. This fixes that. Mypy should have caught this, but oh well.
=> Fix cringo crash at end of turn if DMs can't be sent

crimsobot/cogs/reactions.py
Current behavior is fact_add() will pitch a fit if a user tries to add a fact that is only an attachment without including the semicolon. It would make sense to make an exception in this case and let the command go through anyway, because the message contains a valid fact without text in the fact body.
=> Allow adding fact without semicolon if body only contains attachments

crimsobot/cogs/utilities.py
Reverts crimsobot/crimsoBOT#126
Somehow completely broke the command and now even hex codes that do have the "#" aren't working anymore
=> Revert "Support hex codes missing the "#""

crimsobot/cogs/games.py, crimsobot/models/guess_statistic.py
This is a stopgap measure to alert users to the Discord rate limits that are slowing down the guessmoji game.
=> Stopgap while guessmoji is reconfigured

crimsobot/bot.py, crimsobot/cogs/image.py, crimsobot/data/img/__init__.py, crimsobot/data/img/rules.yaml, crimsobot/exceptions.py, crimsobot/utils/image.py
Alright, lots of changes!
The main course is the image scraper in `cogs/image.py`. I have added a feature where you can use image commands on a recently posted image, not just an image referenced in the message calling the command. You can now run an image command on an image--upload, link, or within an embed!--that's within the past 8 messages. This scraper comes with a custom exception that will notify the user if an image is not found.
In order to allow usage of `>eimg mobile` and `>eimg tablet` in conjunction with the image scraper, I needed to refactor `eimg()` into a command group. This switches the order of input from `>eimg [image] [platform]` to `>eimg [optional:platform] [optional:image]`. This only cost a few lines of code.
More tunable parameters and reference material that …
=> Image scraper and refactoring!

crimsobot/cogs/mystery.py, crimsobot/utils/tarot.py
A new spread, the Celtic Cross, is added. This necessitates the addition of a new argument to be passed to `utils/tarot.py: get_image()`, a bool that indicates a 90° rotation to any card that is meant to be dealt horizontally (i.e. crossed).
=> Celtic cross spread; "cross" card rotation

crimsobot/cogs/mystery.py
The code for formatting and sending an embed is moved to its own function `cogs/mystery.py: tarot_embed()`, and each spread function calls the new function. 
In a perfect world, this code could be even DRYer, but we want those tarot spreads to be separate functions so that they'll show up when `>help tarot` is called.
=> DRYing up the spread functions

crimsobot/cogs/mystery.py, crimsobot/utils/tarot.py
The `tarot_embed()` function is moved from the main `cogs/mystery.py: tarot()` function to `utils/tarot.py` with the rest of the helper functions.
When an argument that was not a subcommand was passed to the `tarot()` commands group, the default behavior was to give the user the "default" spread by calling `ppf()`. (This is also the behavior when `>tarot` is called with no subcommand.) 
If an argument is passed, e.g. `>tarot [some argument]`, and a subcommand is not triggered, I have found that users are typically trying to look up a card. The new behavior calls `card('some argument')`. If no argument is passed, `ppf()` is called.
=> Refactor and new ease of use feature

config.example.py, crimsobot/cogs/utilities.py, crimsobot/exceptions.py, crimsobot/utils/astronomy.py
The `utilities/map` command required an update because both the MapQuest API and the Bitly API had ceased to function; neither are free for use any longer. The command is updated to use the TomTom API, which has a handsome daily allowance of free usage.
The TomTom API more easily allows the user to specify a zoom level, so this functionality has been passed on to the user. From `>help map`:
```
>map <location>
Get a map of a location using its name.
You can also specify a zoom level 1-22.
1 is zoomed out the most; 10 is the default.
Example usage: >map hell; 14
```
This will require that `config.py` be updated, as we have switched from MapQuest to TomTom API. References to `MAPQUEST_API_KEY` are now to `TOMTOM_API_KEY`.
=> Update map command (see PR notes!)

crimsobot/cogs/admin.py, crimsobot/cogs/image.py, crimsobot/cogs/reactions.py, crimsobot/utils/cringo_leaderboard.py, crimsobot/utils/fact_leaderboard.py, crimsobot/utils/games.py, crimsobot/utils/guess_leaderboard.py, crimsobot/utils/image.py, crimsobot/utils/leaderboard.py, crimsobot/utils/tarot.py, crimsobot/utils/wordle.py
With the decision to no longer use discriminators, many strings referring to a user (e.g. `discord.User` or `ctx.author`) have a vestigial discriminator of "#0". I have tried to find every instance of this to avoid displaying the vestigial discriminator:
- `discord.User` becomes `discord.User.name`
- `ctx.author` becomes `ctx.author.name`
- Any call to `discord.User.discriminator` is removed
=> Obliterating every discriminator I could find

crimsobot/cogs/mystery.py
The aliases "three" and "five" were superseding calls for info on any tarot card beginning with three or five. Those aliases are removed.
- **Before**: `>tarot three of cups` would be interpreted as `>tarot three` and return a three-card reading.
- **Now**: `>tarot three of cups` will fail to trigger a find a group command and will revert to `>tarot [card] three of cups` as intended. `>tarot three` returns nothing.
Cooldown timers for all tarot commands have been relaxed from three per 120 seconds to 3 per 45 seconds.
=> Remove command aliases conflicting with card names; relax cooldown timers

crimsobot/cogs/games.py, crimsobot/data/games/rules.yaml, crimsobot/handlers/games.py
(oops, scope creep)
- `>emojistory`: Anonymized submission embed, nixed discriminators
- Transactional commands in `cogs/games` reformatted.
- A few more vestigial discriminators found and removed.
=> Emojistory fixes; few more discrims nixed; oops fixed give/bal commands too

crimsobot/cogs/chat.py, crimsobot/cogs/cringo.py, crimsobot/cogs/games.py, crimsobot/cogs/image.py, crimsobot/cogs/mystery.py, crimsobot/cogs/reactions.py, crimsobot/cogs/text.py, crimsobot/cogs/utilities.py
I rewrote all help text such that each line
- fits in a text block without wrapping,
- at minimum Discord app window size (PC/Mac),
- at 100% zoom.
I feel better now.
=> Constrained width of each line of help text

crimsobot/cogs/image.py, crimsobot/data/img/rules.yaml, crimsobot/utils/image.py
The commands that handle images are a touch resistant to inline arguments, so the user is prompted for further options with an embed. Those embeds, currently in use for `>currents` and `>pingbadge`, have been updated to prompt the user to click on a reaction emoji. Before, they prompted the user to select an option by sending a message.
=> Fix image options embed for currents and pingbadge

crimsobot/cogs/image.py, crimsobot/data/img/rules.yaml
A couple of things to DRY up the image cog.
- A function for handling image processing options is added. The options are a dict whose keys are emojis and values are arguments to pass to the image handler.
- A timeout rule is added to data/img/rules.yaml.
=> Options handler, timeout rule added
